### PR TITLE
GMX-1968 remove poisonous Hashie

### PR DESCRIPTION
**Pull request by mtyeh411**

### CODE REVIEW

**Comment by mtyeh411** [comment]
@jstoup111 @nankrah still need to check any potential downstream effects in application code

cc @asurin

**Comment by asurin** [comment]
Love it!

**Review by nankrah — APPROVED** [review]
👍

**Comment by jstoup111** [comment]
Think it makes sense to use `HashWithIndifferentAccess`.

I know it's an ActiveSupport dependency, but might be worthwhile looking into.

**Comment by jstoup111** [comment]
Looks good otherwise.

**Pull request merged**
