### PR TITLE
fixed Content-Type headers for Server API

### PR DESCRIPTION
**Pull request by mtyeh411**

### CODE REVIEW

**Comment by mtyeh411** [comment]
@jstoup111 (see complete commit message for changes)

**Comment by mtyeh411** [comment]
@weddingwire/gmx please review

**Comment by jstoup111** [comment]
Looks good to me.

**Comment by mtyeh411** [comment]
@jstoup111 check out latest commit ... it actually was not sending any data 😳

**Comment by jstoup111** [comment]
Still looks good to me!

**Pull request merged**
